author: 
    name: Relevance
    homepage: http://relevancellc.c om
summary: Declarative Interface for Rails
homepage: http://streamlinedframework.org
plugin: http://streamlinedframework.com:8079/streamlined/plugins/streamlined
license: MIT